apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: om8d65m89-java-quarkus
  janus-idp.io/tekton: om8d65m89-java-quarkus
  backstage.io/kubernetes-id: om8d65m89-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: om8d65m89-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
